final String agent_label = 'jenkins-jenkins-agent'
final String tf_version = 'tf-1-9-8'

final def task_names = [
    'create',
    'destroy'
]

pipeline {
    agent {
      label "${agent_label}"
    }

    environment {
        UNUSED = credentials('aws-dev-deployer-creds')
    }

    options {
        ansiColor('xterm')
        timeout(time: 30)
    }

    parameters {
        choice choices: task_names,
        description: 'Create or destroy actions',
        name: 'ACTIONS'
    }

    tools {
        terraform "${tf_version}"
    }

    stages{
        stage('confirmation') {
            input {
                message "Continue with deployment?"
                ok "Gogogog1!1!"
            }
            steps {
                sh """
                    echo this will ${params.ACTIONS} the environment
                """
            }
        }

        stage('platforming') {
            steps {
                script {
                    withKubeConfig([credentialsId: 'hive-fleet-k3s-config']) {
                        if (params.ACTIONS == 'create') {
                            sh """
                                echo $KUBECONFIG
                                cp $KUBECONFIG ~/.kube/k3s-config
                                task apps-${params.ACTIONS}
                            """
                        } else {
                            sh """
                                task apps-${params.ACTIONS}
                            """
                        }
                    }
                }
            }
        }
    }
}