final String agent_label = 'jenkins-jenkins-agent'
final String tf_version = 'tf-1-9-2'

final ArrayList task_names = [
    'create',
    'destroy'
]

pipeline {
    agent {
      label "${agent_label}"
    }

    parameters {
        choice choices: task_names,
        description: 'Create or destroy actions',
        name: 'ACTIONS'
    }


    tools {
        terraform "${tf_version}"
    }

    stages{
        stage('platforming') {
            steps {
                script {
                    if (${params.ACTIONS} == 'create') {
                        sh """
                            task ${params.ACTIONS}-apps-local
                        """
                    } else {
                        sh """
                            task ${params.ACTIONS}-apps-local
                        """
                    }
                }
            }
        }
    }
}