final String agent_label = 'jenkins-jenkins-agent'
final String tf_version = 'tf-1-9-8'

final def task_names = [
    'create',
    'destroy'
]

pipeline {
    agent {
      label "${agent_label}"
    }

    options {
        timeout(time: 30)
    }

    parameters {
        choice choices: task_names,
        description: 'Create or destroy actions',
        name: 'ACTIONS'
    }

    tools {
        terraform "${tf_version}"
    }

    stages{
        stage('confirmation') {
            input {
                message "Continue with deployment?"
                ok "Gogogog1!1!"
            }
            steps {
                sh "echo this will ${params.ACTIONS} the environment"
            }
        }

//         stage('install task') {
//             steps {
//                 sh '''
//                     sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~
//                 '''
//             }
//         }

        stage('platforming') {
            steps {
                script {
                    withKubeConfig([credentialsId: 'hive-fleet-k3s-config', serverUrl: 'https://192.168.109.188:6443']) {
                        if (params.ACTIONS == 'create') {
                            sh """
                                kubectl version
                                /home/jenkins/task apps-${params.ACTIONS}
                            """
                        } else {
                            sh """
                                /home/jenkins/task apps-${params.ACTIONS}
                            """
                        }
                    }
                }
            }
        }
    }
}