final String agentLabel = 'jenkins-agent'
final String awsCreds = 'aws-dev-deployer-creds'
final String tfVersion = 'tf-1-9-8'

final def distros = [
    'oracle',
    'rocky',
    'ubuntu'
]

final def distroFamily = [
    'debian',
    'red_hat'
]

final def isoNames = [
    'OracleLinux-R9-U4-x86_64-boot.iso',
    'Rocky-9.4-x86_64-boot.iso',
    'debian-12.7.0-amd64-netinst.iso',
    'ubuntu-24.04.1-live-server-amd64.iso'
]

final def proxmoxNodes = [
    'behemoth',
    'kraken',
    'leviathan'
]

pipeline {
    agent {
      label agentLabel
    }

    environment {
        UNUSED = credentials("${awsCreds}")
    }

    options {
        ansiColor('xterm')
        timeout(
            time: 8,
            unit: 'MINUTES'
        )
    }

    parameters {
        choice choices: distros,
        description: 'linux distribution',
        name: 'DISTRIBUTION'

        choice choices: isoNames,
        description: 'iso names',
        name: 'ISO_NAME'

        choice choices: proxmoxNodes,
        description: 'proxmox nodes',
        name: 'PROXMOX_NODE'

        string description: 'template description',
        trim: true,
        name: 'TEMPLATE_DESC'

        string description: 'template name',
        trim: true,
        name: 'TEMPLATE_NAME'
    }

    tools {
        terraform "${tfVersion}"
    }

    stages {
        stage('confirmation') {
            input {
                message "Continue with deployment?"
                ok "Gogogog1!1!"
            }
            steps {
                println "building a Proxmox template from ${params.ISO_NAME}"
            }
        }

        stage('packing image') {
            steps {
                script {
                    println "${params.DISTRIBUTION}"
                    println "${params.ISO_NAME}"
                    println "${params.PROXMOX_NODE}"
                    println "${params.TEMPLATE_DESC}"
                    println "${params.TEMPLATE_NAME}"
                }
            }
        }
    }
}