final String agentLabel = 'jenkins-agent'
final String awsCreds = 'aws-dev-deployer-creds'
final String tfVersion = 'tf-1-9-8'

final def distros = [
    'ol', # oracle linux
    'rl', # rocky linux
    'ubu' # ubuntu
]

final def distroFamily = [
    'debian',
    'red_hat'
]

final def isoNames = [
    'OracleLinux-R9-U4-x86_64-boot.iso',
    'Rocky-9.4-x86_64-boot.iso',
    'debian-12.7.0-amd64-netinst.iso',
    'ubuntu-24.04.1-live-server-amd64.iso'
]

final def proxmoxNodes = [
    'behemoth',
    'kraken',
    'leviathan'
]

final def taskNames = [
    'build',
    'demolish'
]

pipeline {
    agent {
      label agentLabel
    }

    environment {
        UNUSED = credentials("${awsCreds}")
    }

    options {
        ansiColor('xterm')
        timeout(
            time: 8,
            unit: 'MINUTES'
        )
    }

    parameters {
        choice choices: taskNames,
        description: 'Create or destroy actions',
        name: 'ACTIONS'

        choice choices: distros,
        description: 'Linux distributions',
        name: 'DISTRO'

        choice choices: distroFamily,
        description: 'Linux family distribution',
        name: 'DISTRO_FAMILY'

        choice choices: isoNames,
        description: 'ISO names',
        name: 'ISO_NAME'

        choice choices: proxmoxNodes,
        description: 'Proxmox nodes',
        name: 'PROXMOX_NODE'

        string description: 'Template name'
        trim: true
        name: 'TMPL_NAME'
    }

    tools {
        terraform "${tfVersion}"
    }

    stages {
        stage('confirmation') {
            input {
                message "Continue with deployment?"
                ok "Gogogog1!1!"
            }
            steps {
                sh """
                    echo this will ${params.ACTIONS} an image from ${params.ISO_NAME} image
                """
            }
        }

        stage('packing image') {
            steps {
                script {
                    if (params.ACTIONS == 'build') {
                        sh """
                            echo ${params.ACTIONS}
                            echo ${params.DISTRO}
                            echo ${params.DISTRO_FAMILY}
                            echo ${params.ISO_NAME}
                            echo ${params.PROXMOX_NODE}
                            echo ${params.TMPL_NAME}
                        """
                    } else {
                        sh """
                            task packer-${params.DISTRIBUTION}-${params.ACTIONS}
                        """
                    }
                }
            }
        }
    }
}