{
 "title": "Usage 2",
 "tags": [
  "cloudwatch",
  "containerinsights"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "us-gov-west-1, us-gov-east-1" },
   {
    "name": "clustername",
    "label": "ClusterName",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Avg CPU Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace" },
     "metricName": "pod_cpu_utilization",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Avg Memory Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace" },
     "metricName": "pod_memory_utilization",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Enforcers connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "aqua" },
     "metricName": "namespace_number_of_running_pods",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "$region",
     "sql": {
      "from": { "property": { "name": "ContainerInsights", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        {
         "name": "namespace_number_of_running_pods",
         "type": "functionParameter"
        }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(namespace_number_of_running_pods) FROM ContainerInsights",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Scanners connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace" },
     "metricName": "namespace_number_of_running_pods",
     "namespace": "ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$clustername" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "$region",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}