ARG VERSION=10.1-minimal

FROM docker.io/rockylinux/rockylinux:${VERSION}

ARG USER=pkg-bldr

RUN microdnf upgrade -y

RUN microdnf install \
    --setopt=install_weak_deps=0 \
    --nodocs \
    --refresh \
    -y \
    epel-release

RUN echo "sslverify=0" >> /etc/dnf/dnf.conf

RUN microdnf install \
    --setopt=install_weak_deps=0 \
    --nodocs \
    --refresh \
    -y \
    gcc \
    git \
    make \
    openssh-clients \
    pinentry-tty \
    rng-tools \
    rpm-build \
    rpm-sign \
    rsync

RUN sed -i '/sslverify=0/d' /etc/dnf/dnf.conf

RUN microdnf clean all

RUN rm -rf /etc/yum.repos.d

RUN useradd -m -s /bin/bash ${USER}

WORKDIR /home/${USER}

USER ${USER}