ARG VERSION=9.3-minimal
ARG TF_VERSION=1.14.5

FROM rockylinux:$VERSION


RUN dnf up -y

RUN dnf --setopt=install_weak_deps=False install \
    --refresh \
    -y \
    git \
    httpd-tools \
    unzip

# Install Awscli v2
RUN curl -LO "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
    && unzip awscli-exe-linux-x86_64.zip \
    && sh ./aws/install \
    && rm -rf aws*

# Install taskfile
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

# Installs kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Installs terraform
RUN curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip \
    && unzip terraform_${TF_VERSION}_linux_amd64.zip \
    && rm -f LICENSE.txt terraform_${TF_VERSION}_linux_amd64.zip \
    && mv terraform /usr/local/bin/


