ARG VERSION=9.3-minimal

FROM rockylinux:${VERSION}

ARG TF_VERSION=1.14.5

RUN microdnf upgrade -y

RUN microdnf --setopt=install_weak_deps=0 install \
    --nodocs \
    --refresh \
    -y \
    git \
    httpd-tools \
    tar \
    unzip

# Install Awscli v2
RUN curl -LO "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
    && unzip awscli-exe-linux-x86_64.zip \
    && sh ./aws/install \
    && rm -rf aws*

# Install Cosign
RUN curl -LO "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64" \
    && mv cosign-linux-amd64 /usr/local/bin/cosign \
    && chmod +x /usr/local/bin/cosign

# Install taskfile
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

# Installs kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Installs terraform
RUN curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip \
    && unzip terraform_${TF_VERSION}_linux_amd64.zip \
    && rm -f LICENSE.txt terraform_${TF_VERSION}_linux_amd64.zip \
    && mv terraform /usr/local/bin/

# create non-root user
RUN useradd -ms /bin/bash phil
WORKDIR /home/phil

USER phil