final String agent_label = 'jenkins-jenkins-agent'

pipeline {
    agent {
      label "${agent_label}"
    }

    options {
        timeout(
            time: 5,
            unit: 'MINUTES'
        )
    }

    parameters {
        string(
            description: 'Tag for Jenkins agent',
            name: 'JENKINS_AGENT_TAG',
            trim: true
        )
    }

    stages{
        stage('building image') {
            steps {
                script {
                    withCredentials(
                        [
                            usernamePassword(
                                credentialsId: 'docker-hub-creds',
                                usernameVariable: 'USERNAME',
                                passwordVariable: 'PASSWORD'
                            )
                        ]
                    ) {
                            sh """
                                printenv
                                docker version
                                echo ${PASSWORD} | docker login --username ${USERNAME} --password-stdin
                                task build-jagent-image JENKINS_AGENT_TAG=${params.JENKINS_AGENT_TAG}
                                task push-jagent-image JENKINS_AGENT_TAG=${params.JENKINS_AGENT_TAG}
                            """
                    }
                }
            }
        }
    }
}