final String agent_label = 'jenkins-jenkins-agent'

pipeline {
    agent {
      label "${agent_label}"
    }

    parameters {
        string(
            name: 'DOCKER_HUB_USER',
            defaultValue: '',
            description: 'Username for Docker Hub'
            trim: true
        )
    }

    options {
        timeout(
            time: 5,
            unit: 'MINUTES'
        )
    }

    stages{
        stage('building image') {
            steps {
                script {
                    withCredentials(
                        [
                            usernamePassword(
                                credentialsId: 'docker-hub-creds',
                                usernameVariable: 'USERNAME',
                                passwordVariable: 'PASSWORD'
                            )
                        ]
                    ) {
                            sh """
                                echo user: ${params.DOCKER_HUB_USER}
                                echo ${USERNAME}
                                echo ${PASSWORD}
                                docker version
                                task build-jagent-image
                                task push-jagent-image
                            """
                    }
                }
            }
        }
    }
}