@Library("devops-lib")
_

final String agent_label = 'jenkins-agent'
final String aws_creds = 'aws-dev-deployer-creds'
final String tf_version = 'tf-1-9-8'

import com.pafable.PipelineArgs

pipeline {
    agent {
      label agent_label
    }

    environment {
        UNUSED = credentials("${aws_creds}")
    }

    options {
        ansiColor('xterm')
        timeout(
            time: 5,
            unit: 'MINUTES'
        )
    }

    parameters {
        choice choices: PipelineArgs.taskActions,
        description: PipelineArgs.taskDesc,
        name: PipelineArgs.taskName
    }

    tools {
        terraform "${tf_version}"
    }

    stages {
        stage('updating dns') {
            steps {
                script {
                    if (params.ACTIONS == 'create') {
                        sh """
                            task dns-entries-${params.ACTIONS}
                        """
                    } else {
                        sh """
                            task dns-entries-${params.ACTIONS}
                        """
                    }
                }
            }
        }
    }
}