@Library("devops-libs")
_

final String agent_label = 'jenkins-agent'
final String tf_version = 'tf-1-9-8'

import com.pafable.PipelineArgs

pipeline {
    agent {
      label "${agent_label}"
    }

    environment {
        UNUSED = credentials('aws-dev-deployer-creds')
    }

    options {
        ansiColor('xterm')
        timeout(
            time: 5,
            unit: 'MINUTES'
        )
    }

    parameters {
        choice choices: PipelineArgs.taskActions,
        description: PipelineArgs.taskDesc,
        name: PipelineArgs.taskName
    }

    tools {
        terraform "${tf_version}"
    }

    stages {
        stage('confirmation') {
            input {
                message "Continue with deployment?"
                ok "Gogogog1!1!"
            }
            steps {
                sh """
                    echo this will ${params.ACTIONS} the environment
                """
            }
        }

        stage('platforming') {
            steps {
                withKubeConfig([credentialsId: 'hive-fleet-k3s-config']) {
                    sh """
                        kubectl get nodes
                    """
//                     script {
//                         sh """
//                             mkdir ~/.kube
//                             ln -s $KUBECONFIG ~/.kube/k3s-config
//                         """
//                         if (params.ACTIONS == 'create') {
//                             sh """
//                                 task apps-${params.ACTIONS}
//                             """
//                         } else {
//                             sh """
//                                 task apps-${params.ACTIONS}
//                             """
//                         }
//                     }
                }
            }
        }
    }
}