pipeline {
    agent {
      label 'jenkins-jenkins-agent'
    }

    options {
        timeout(
            time: 1,
            unit: 'MINUTES'
        )
    }

    tools {
      terraform 'tf-1-9-2'
    }


    stages {
        stage('Hello') {
            steps {
                echo 'hello this is a seed job'
            }
        }

        stage('tf check') {
            steps {
                sh 'terraform version'
            }
        }

        stage('sleep') {
            steps {
                sh 'sleep 5m'
            }
        }
    }
}