ARG VERSION=10.1-minimal

FROM rockylinux/rockylinux:${VERSION}

ARG USER=pkg-bldr

RUN microdnf upgrade -y

RUN microdnf install \
    --setopt=install_weak_deps=0 \
    --nodocs \
    --refresh \
    -y \
    epel-release

# Sets sslverify=0 to avoid "Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist" error when running microdnf install
RUN echo 'sslverify=0' >> /etc/dnf/dnf.conf

RUN microdnf install \
    --setopt=install_weak_deps=0 \
    --nodocs \
    --refresh \
    -y \
    gcc \
    make \
    rpm-build \
    rpmdevtools \
    rsync

# removes sslverify=0
RUN sed -i '/^sslverify=0$/d' /etc/dnf/dnf.conf

RUN microdnf clean all

RUN rm -rf /etc/yum.repos.d

RUN useradd -m -s /bin/bash ${USER}

WORKDIR /home/${USER}

USER ${USER}

RUN rpmdev-setuptree