locals {
  plugins = [
    "ansicolor",
    "blueocean",
    "configuration-as-code",
    "docker-workflow",
    "git",
    "github",
    "javax-mail-api",
    "job-dsl",
    "kubernetes",
    "login-theme",
    "matrix-auth",
    "pipeline-aws",
    "pipeline-build-step",
    "pipeline-stage-view",
    "prometheus",
    "rebuild",
    "role-strategy",
    "sshd",
    "timestamper",
    "terraform",
    "trilead-api",
    "workflow-aggregator",
    "ws-cleanup",
  ]
}