apiVersion: v1
kind: Service
metadata:
  {{ if eq .Values.app.env.NODE_ENV "development" -}}
  name: {{ .Values.app.name }}-svc-dev
  {{ else if eq .Values.app.env.NODE_ENV "production" -}}
  name: {{ .Values.app.name }}-svc-prod
  {{ else }}
  {{ fail "Entry in .Values.app.env.NODE_ENV is not recognized" }}
  {{ end }}
  namespace: {{ include  "my-app.namespace" . }}
  labels:
    {{ if eq .Values.app.env.NODE_ENV "development" -}}
    app.kubernetes.io/name: {{ .Values.app.name }}-dev
    jobLabel: {{ .Values.app.name }}-dev
    {{ else if eq .Values.app.env.NODE_ENV "production" -}}
    app.kubernetes.io/name: {{ .Values.app.name }}-prod
    jobLabel: {{ .Values.app.name }}-prod
    {{ else }}
    {{ fail "Entry in .Values.app.env.NODE_ENV is not recognized" }}
    {{ end }}
spec:
  selector:
    {{ if eq .Values.app.env.NODE_ENV "development" -}}
    app.kubernetes.io/name: {{ .Values.app.name }}-dev
    {{ else if eq .Values.app.env.NODE_ENV "production" -}}
    app.kubernetes.io/name: {{ .Values.app.name }}-prod
    {{ else }}
    {{ fail "Entry in .Values.app.env.NODE_ENV is not recognized" }}
    {{ end }}
  ports:
    - name: {{ .Values.app.name }}-port
      protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port }}