# this is being deployed here terraform/modules/argocd/apps.tf:2
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-example-app-dev
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argo-example-app
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-webapp
    repoURL: 'https://github.com/pafable/argo-examples'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2