name: Create Dev Atlantis

on:
  workflow_dispatch

env:
  ATLANTIS_DIR: terraform/atlantis
  TF_PLAN_FILE: tfplan
  TF_VERSION: 1.8.2
  TF_WORKSPACE: dev

jobs:
  create-atlantis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.0
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.ATLANTIS_DIR }}
        run: |
          terraform init \
            -backend-config="bucket=YOUR_TF_BACKEND_DEV" \
            -backend-config="encrypt=true" \
            -backend-config="key=terraform/atlantis/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -upgrade \
            -reconfigure

      - name: Terraform Plan
        working-directory: ${{ env.ATLANTIS_DIR }}
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          COMMIT=$(git rev-parse HEAD)
          terraform plan \
            -var-file=terraform.tfvars \
            -var "github_token=${{ secrets.GH_TOKEN }}" \
            -var "github_webhook_secret=${{ secrets.GH_WEBHOOK_SECRET }}" \
            -out ${{ env.TF_PLAN_FILE }}

      - name: Terraform Apply
        working-directory: ${{ env.ATLANTIS_DIR }}
        run: |
          terraform apply ${{ env.TF_PLAN_FILE }}
          rm -f ${{ env.TF_PLAN_FILE }}