name: Create Dev EKS Cluster

on:
  workflow_dispatch

env:
  DNS_ZONE: YOUR_DNS_ZONE
  DNS_DIR: terraform/aws/dns
  EKS_DIR: terraform/aws/eks
  KUBE_SUPPORT_DIR: terraform/aws/kube-support
  TF_PLAN_FILE: tfplan
  TF_VERSION: 1.9.2
  TF_WORKSPACE: dev

jobs:
  terraform-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.0
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Deploy Cluster
        working-directory: ${{ env.EKS_DIR }}
        run: task create-cluster